apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: 590183884787.dkr.ecr.us-west-2.amazonaws.com/sravs
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: web-ssvc
spec:
  selector:
    app: web
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: NodePort # type of the service.
